name: help_a_paw
description: Help A Paw in Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  permission_handler: ^10.2.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.17
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  google_sign_in: ^6.0.2
  url_launcher: ^6.1.10
  social_login_buttons: ^1.0.7
  cloud_firestore: ^4.4.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/