name: help_a_paw
description: Send emergency signals about animals in need
publish_to: 'none' 
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  adaptive_components: ^0.0.9
  adaptive_navigation: ^0.0.9
  animations: ^2.0.8
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.2.0+1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_in_app_messaging: ^0.7.3+7
  firebase_messaging: ^14.6.9
  go_router: ^11.1.4
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.3

environment:
  sdk: '>=3.0.0 <6.0.0'

flutter:
  assets:
    - lib/assets/
  uses-material-design: true
