name: flutter-application
base: core20
confinement: strict
description: |
  Flutter Application
summary: Flutter Application
version: 'latest'

apps:
  flutter-application:
    command: bin/linux/flutter_application
    extensions: [flutter-dev]

parts:
  flutter-application:
    flutter-target: lib/main.dart
    plugin: flutter
    source:
    source-type: git