import XCTest

/// Locks `Geohash` to `geoflutterfire_plus`'s output.
///
/// The Swift twin of `android/app/src/test/kotlin/.../GeohashTest.kt`, pinning
/// the same vectors — the encoder exists three times (Dart, Kotlin, Swift) and
/// all three must agree byte for byte.
///
/// These are not arbitrary fixtures: every expected value was generated by the
/// Dart implementation the app already uses (`GeoFirePoint.geohash`). The
/// background monitor writes `userLocations/{uid}` natively, and the
/// notification fan-out finds nearby users with a geohash *range* query. If this
/// encoder drifts — a different alphabet, a different precision, an off-by-one
/// in the bit interleave — the user's document sorts into the wrong range and
/// they simply stop receiving notifications. Nothing throws and nothing logs, so
/// this test is the only thing standing between a subtle edit and a silent
/// outage.
class GeohashTest: XCTestCase {

  private func assertGeohash(
    _ expected: String,
    _ latitude: Double,
    _ longitude: Double,
    file: StaticString = #filePath,
    line: UInt = #line
  ) {
    XCTAssertEqual(
      Geohash.encode(latitude: latitude, longitude: longitude),
      expected,
      "geohash mismatch for (\(latitude), \(longitude))",
      file: file,
      line: line
    )
  }

  func testMatchesGeoflutterfirePlusForTypicalCoordinates() {
    // Sofia — the app's fallback map centre.
    assertGeohash("sx8dfsykp", 42.6977, 23.3219)
    // London: negative longitude, positive latitude.
    assertGeohash("gcpvj0duq", 51.5074, -0.1278)
    // Sydney: southern and eastern hemispheres.
    assertGeohash("r3gx2f77b", -33.8688, 151.2093)
  }

  func testMatchesGeoflutterfirePlusAtBoundaries() {
    // The equator/prime-meridian origin, where every bit comparison is against
    // an exact midpoint — the classic place for an off-by-one.
    assertGeohash("7zzzzzzzz", 0.0, 0.0)
    assertGeohash("7zzzzzzzm", -0.0001, -0.0001)

    // Extremes of the coordinate space.
    assertGeohash("zzzzzzzzm", 89.9999, 179.9999)
    assertGeohash("00000000d", -89.9999, -179.9999)
  }

  func testUsesThePrecisionTheFanOutRangeQueryExpects() {
    XCTAssertEqual(Geohash.defaultPrecision, 9)
    XCTAssertEqual(Geohash.encode(latitude: 42.6977, longitude: 23.3219).count, 9)
  }

  func testNeverEmitsCharactersOutsideTheBase32Alphabet() {
    // geoflutterfire_plus omits a, i, l and o. Emitting one would sort
    // incorrectly against hashes written by the Dart path.
    let allowed = Set("0123456789bcdefghjkmnpqrstuvwxyz")
    for latitude in stride(from: -89.0, through: 89.0, by: 17.0) {
      for longitude in stride(from: -179.0, through: 179.0, by: 23.0) {
        let hash = Geohash.encode(latitude: latitude, longitude: longitude)
        XCTAssertEqual(
          Set(hash).subtracting(allowed),
          [],
          "unexpected characters in \(hash) for (\(latitude), \(longitude))"
        )
      }
    }
  }
}
