import XCTest

/// Fails the build if anything in `ios/Runner/` touches Firestore natively.
///
/// The iOS twin of `test/firestore_settings_guard_test.dart`: both guard the
/// same boundary from the two sides it can be broken from.
///
/// `FLTFirebaseFirestorePlugin.getFIRFirestoreFromAppNameFromPigeon` assigns
/// `firestore.settings` on the first Dart-side Firestore call, assuming it is
/// the only thing in the process that ever created the default instance. If
/// native code called `Firestore.firestore()` first, the client is already
/// started, `Firestore::set_settings` throws `IllegalState`, the plugin does
/// not catch it and the process aborts. That is a **SIGABRT at launch, for
/// every user, on every launch** — and one that is easy to misattribute,
/// because the entry frame varies with whatever else is booting.
///
/// This is why the `userLocations/{uid}` write is native on Android but
/// deliberately Dart-side on iOS (`LocationService._onBackgroundLocation`),
/// which costs nothing there: a significant-change delivery relaunches the
/// whole app anyway. Adding a native write back "for symmetry with Android" is
/// exactly the change this test exists to stop.
///
/// The scan strips comments first, so the doc comment on
/// `BackgroundLocationManager` that spells the rule out — naming the very
/// symbols banned here — does not trip it.
class NativeFirestoreGuardTest: XCTestCase {

  /// Names that can only appear in code that reaches the Firestore SDK.
  private static let bannedPatterns = [
    "Firestore.firestore()",
    "FirebaseFirestore",
    "FIRFirestore",
  ]

  /// Generated by `flutter build`; it registers the plugin, which is the one
  /// thing that is *supposed* to own the default instance.
  private static let generatedFiles: Set<String> = [
    "GeneratedPluginRegistrant.m",
    "GeneratedPluginRegistrant.h",
  ]

  func testNoNativeCodeCreatesTheDefaultFirestoreInstance() throws {
    let runner = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()  // RunnerTests
      .deletingLastPathComponent()  // ios
      .appendingPathComponent("Runner")

    let sources = try FileManager.default
      .contentsOfDirectory(at: runner, includingPropertiesForKeys: nil)
      .filter { ["swift", "m", "mm", "h"].contains($0.pathExtension) }
      .filter { !Self.generatedFiles.contains($0.lastPathComponent) }
      .sorted { $0.lastPathComponent < $1.lastPathComponent }

    XCTAssertFalse(
      sources.isEmpty,
      "found no sources under \(runner.path) — the guard would pass vacuously")

    var offenders: [String] = []
    for source in sources {
      let code = Self.strippingCommentsAndStrings(
        try String(contentsOf: source, encoding: .utf8))
      for (index, line) in code.components(separatedBy: "\n").enumerated() {
        for pattern in Self.bannedPatterns where line.contains(pattern) {
          offenders.append(
            "\(source.lastPathComponent):\(index + 1): \(line.trimmingCharacters(in: .whitespaces))"
          )
        }
      }
    }

    XCTAssertEqual(
      offenders, [],
      """
      Native iOS code must never create the default Firestore instance: the \
      cloud_firestore plugin then aborts the process on its first Dart-side \
      call (SIGABRT at launch, every user, every launch). Do the write from \
      Dart instead, as LocationService._onBackgroundLocation does. See the doc \
      comment on this test before changing it.
      \(offenders.joined(separator: "\n"))
      """)
  }

  // MARK: - Comment stripping

  /// Blanks out comments and string literals, preserving line numbering.
  ///
  /// Handles `//`, nested `/* */` (Swift allows nesting), `"..."` with escapes
  /// and `"""..."""`. Deliberately simple — it only has to be conservative
  /// enough that a banned symbol in real code is never blanked out.
  static func strippingCommentsAndStrings(_ source: String) -> String {
    var out = ""
    let chars = Array(source)
    var i = 0
    var blockDepth = 0

    func peek(_ offset: Int) -> Character? {
      let j = i + offset
      return j < chars.count ? chars[j] : nil
    }

    while i < chars.count {
      let c = chars[i]

      if blockDepth > 0 {
        if c == "/" && peek(1) == "*" {
          blockDepth += 1
          i += 2
        } else if c == "*" && peek(1) == "/" {
          blockDepth -= 1
          i += 2
        } else {
          if c == "\n" { out.append(c) }
          i += 1
        }
        continue
      }

      if c == "/" && peek(1) == "*" {
        blockDepth = 1
        i += 2
        continue
      }

      if c == "/" && peek(1) == "/" {
        while i < chars.count && chars[i] != "\n" { i += 1 }
        continue
      }

      if c == "\"" {
        let isMultiline = peek(1) == "\"" && peek(2) == "\""
        i += isMultiline ? 3 : 1
        while i < chars.count {
          if chars[i] == "\\" {
            i += 2
            continue
          }
          if isMultiline {
            if chars[i] == "\"" && peek(1) == "\"" && peek(2) == "\"" {
              i += 3
              break
            }
            if chars[i] == "\n" { out.append("\n") }
            i += 1
          } else {
            if chars[i] == "\"" || chars[i] == "\n" {
              i += 1
              break
            }
            i += 1
          }
        }
        continue
      }

      out.append(c)
      i += 1
    }

    return out
  }

  func testStripperKeepsCodeAndDropsComments() {
    let stripped = Self.strippingCommentsAndStrings(
      """
      // Firestore.firestore() in a line comment
      /* FirebaseFirestore in a block /* nested FIRFirestore */ still block */
      let banner = "FirebaseFirestore in a string"
      let db = Firestore.firestore()
      """)

    XCTAssertFalse(stripped.contains("in a line comment"))
    XCTAssertFalse(stripped.contains("in a block"))
    XCTAssertFalse(stripped.contains("nested"))
    XCTAssertFalse(stripped.contains("in a string"))
    XCTAssertTrue(stripped.contains("Firestore.firestore()"))
    // Line numbering survives, so offender lines point at the real source.
    XCTAssertEqual(stripped.components(separatedBy: "\n").count, 4)
  }
}
