package org.helpapaw.helpapaw

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Locks [Geohash] to `geoflutterfire_plus`'s output.
 *
 * These are not arbitrary fixtures: every expected value was generated by the
 * Dart implementation the app already uses (`GeoFirePoint.geohash`). The
 * background receiver writes `userLocations/{uid}` natively, and the
 * notification fan-out finds nearby users with a geohash *range* query. If this
 * encoder drifts — a different alphabet, a different precision, an off-by-one
 * in the bit interleave — the user's document sorts into the wrong range and
 * they simply stop receiving notifications. Nothing throws and nothing logs, so
 * this test is the only thing standing between a subtle edit and a silent
 * outage.
 */
class GeohashTest {

    private fun assertGeohash(expected: String, latitude: Double, longitude: Double) {
        assertEquals(
            "geohash mismatch for ($latitude, $longitude)",
            expected,
            Geohash.encode(latitude, longitude),
        )
    }

    @Test
    fun `matches geoflutterfire_plus for typical coordinates`() {
        // Sofia — the app's fallback map centre.
        assertGeohash("sx8dfsykp", 42.6977, 23.3219)
        // London: negative longitude, positive latitude.
        assertGeohash("gcpvj0duq", 51.5074, -0.1278)
        // Sydney: southern and eastern hemispheres.
        assertGeohash("r3gx2f77b", -33.8688, 151.2093)
    }

    @Test
    fun `matches geoflutterfire_plus at boundaries`() {
        // The equator/prime-meridian origin, where every bit comparison is
        // against an exact midpoint — the classic place for an off-by-one.
        assertGeohash("7zzzzzzzz", 0.0, 0.0)
        assertGeohash("7zzzzzzzm", -0.0001, -0.0001)

        // Extremes of the coordinate space.
        assertGeohash("zzzzzzzzm", 89.9999, 179.9999)
        assertGeohash("00000000d", -89.9999, -179.9999)
    }

    @Test
    fun `uses the precision the fan-out range query expects`() {
        assertEquals(9, Geohash.DEFAULT_PRECISION)
        assertEquals(9, Geohash.encode(42.6977, 23.3219).length)
    }

    @Test
    fun `never emits characters outside the base32 alphabet`() {
        // geoflutterfire_plus omits a, i, l and o. Emitting one would sort
        // incorrectly against hashes written by the Dart path.
        val allowed = "0123456789bcdefghjkmnpqrstuvwxyz".toSet()
        for (lat in -89..89 step 17) {
            for (lon in -179..179 step 23) {
                val hash = Geohash.encode(lat.toDouble(), lon.toDouble())
                assertEquals(
                    "unexpected characters in $hash",
                    emptySet<Char>(),
                    hash.toSet() - allowed,
                )
            }
        }
    }
}
