name: Flutter

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Install Flutter
      run: sudo snap install flutter --classic

    - name: Run Doctor
      run: flutter doctor
      
    - name: Analyze Package
      run: flutter analyze lib

    - name: Environment Information
      run: dart info
   
    - name: Fix Package Dry Run 
      run: dart fix lib --dry-run
   
    - name: Fix Package Apply
      run: dart fix lib --apply
      
    - name: Dependency Graph
      run: flutter pub deps
      
    - name: Upgrade Packages
      run: flutter pub upgrade
      
    - name: Run Test
      run: flutter test
