name: Flutter

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1.5.0
      
    - name: Install Flutter
      run: sudo snap install flutter --classic
      
    - name: Analyze Package
      run: flutter analyze lib

    - name: Environment Information
      run: dart info
      
    - name: Fix Package
      run: dart fix lib --dry-run
   
    - name: Fix Package
      run: dart fix lib --apply
      
    - name: Format Package 
      run: dart format lib
      
    - name: Get Packages
      run: flutter pub get
      
    - name: Dependency Graph
      run: flutter pub deps
      
    - name: Upgrade Packages
      run: flutter pub upgrade
